; 快捷键部分
$!LButton::Send("^LButton")
$!c::Send("^c")
$!x::Send("^x")
$!v::Send("^v")
$!a::Send("^a")
$!s::Send("^s")
$!w::Send("^w")
$!z::Send("^z")
$!r::Send("^r")
$!t::Send("^t")
$!q::Send("!{F4}")
$!f::Send("^f")
$!/::Send("^/")
